# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTQ1Yjg5YmJjZGY3NGRjYzU3ZDVjNGJkZWRhODRmNmZiYTczMzZlMmQ1NGMyNzBlMzFiNzU5MDhiMDg4ZDBlMGNjMDIwMDU4Yzc5NmE4YTcyMDY0YTE5MDc1ZTBkNTQ4NzVkOTlmZjU0YTA2NjRiY2ZlOGZmM2U3MDljNmNhMWM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
